-- Proposed migration; review against the live Supabase schema before applying.
-- Assumption: public.nodes.node_id is bigint, as in the Python service contract.

create table if not exists public.node_baseline (
    node_id bigint primary key references public.nodes(node_id),
    baseline_displacement_mm double precision not null,
    installed_at timestamptz not null,
    gnss_latitude double precision,
    gnss_longitude double precision,
    coordinate_reference text,
    created_at timestamptz not null default now()
);

create table if not exists public.twin_state (
    id bigint generated by default as identity primary key,
    node_id bigint references public.nodes(node_id),
    cell_id text,
    mine_type text not null check (mine_type in ('longwall', 'bord_and_pillar')),
    expected_deformation_mm double precision,
    susceptibility_score double precision check (susceptibility_score between 0 and 1),
    observed_cumulative_displacement_mm double precision,
    physics_deviation_index double precision check (physics_deviation_index between 0 and 1),
    uncertainty_band_mm double precision check (uncertainty_band_mm > 0),
    parameter_basis jsonb not null,
    is_hypothetical boolean not null default false check (is_hypothetical = false),
    computed_at timestamptz not null default now()
);

create index if not exists twin_state_node_computed_at_idx
    on public.twin_state (node_id, computed_at desc);

alter table public.predictions
    add column if not exists risk_score double precision check (risk_score between 0 and 1),
    add column if not exists confidence_badge text check (confidence_badge in ('agreeing', 'mixed', 'disagreeing'));
